#ifndef GRAPHIC_CONTROL_PANEL_GLOBAL_H
#define GRAPHIC_CONTROL_PANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHIC_CONTROL_PANEL_LIBRARY)
#  define GRAPHIC_CONTROL_PANELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRAPHIC_CONTROL_PANELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHIC_CONTROL_PANEL_GLOBAL_H
